config/routes.rb
Littlegeodesignworld::Application.routes.draw do
  root :to => "site#land"

  resources :question_comments
  resources :questions
  resources :action_item_comments
  resources :action_items
  resources :people
  
  match '/questions/:id/vote_up' => 'questions#vote_up', :as => :vote_up_question
  match '/action_items/:id/vote_up' => 'action_items#vote_up', :as => :vote_up_action_item
  match '/action_items/:id/take_on' => 'action_items#take_on', :as => :take_on_action_item

  devise_for :admins
  devise_for :persons
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :person
  has_many :question_comments
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authenticate_person!
  
  # GET /questions
  # GET /questions.xml
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.xml
  def show
    @question = Question.find(params[:id])
    
    @question_comment = QuestionComment.new

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.xml
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.xml
  def create
    @question = Question.new(params[:question])
    @question.person = current_person

    respond_to do |format|
      if @question.save
        format.html { redirect_to("/", :notice => 'Question was successfully created.') }
        format.xml  { render :xml => @question, :status => :created, :location => @question }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.xml
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to("/", :notice => 'Question was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.xml
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to(questions_url) }
      format.xml  { head :ok }
    end
  end
  
  def vote_up
    @question = Question.find(params[:id])
    if !@question.votes
      @question.votes = 0
    end
    @question.votes = @question.votes + 1

    respond_to do |format|
      if @question.save()
        format.html { redirect_to(@question, :notice => 'Your vote was recorded.') }
      end
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <tr>
    <th>Body</th>
    <th>Author</th>
    <th>Votes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.body %></td>
    <td><%= question.author_id %></td>
    <td><%= question.votes %></td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1><img src="/images/logo.png" alt="GeodesignWorld"/>
<h2>Add a New Question</h2>

<%= render 'form' %>

<p><%= link_to 'Never mind. Take me back to the main page.', root_path %></p>

app/views/questions/show.html.erb
<% content_for :head do %>
<script>
$(document).ready(function() {
  $('#add-a-comment-link').click(function() {
    $('#add-a-comment-link').hide();
    $('#add-a-comment-form').show();
  });
});
</script>
<style>
label {
  display: none;
}
</style>
<% end %>

<h1><a href="/"><img src="/images/logo.png" alt="GeodesignWorld"/></a></h1>
<%= link_to 'Take me back to the main page.', root_path, :id => 'sign-out-block' %>
<h2>A Question</h2>

<p style="font-size:24px;"><%= @question.body %></p>
<p>&nbsp;</p>
<p>Originally posted by: <%= link_to @question.person.name, @question.person %></p>
<p>&nbsp;</p>
<p><%= pluralize(@question.votes, 'vote') %> <%= link_to "This is good. Add my vote.", vote_up_question_path(@question) %></p>
<p>&nbsp;</p>
<a href="#" id="add-a-comment-link">Add a Comment</a>
<h2><%= pluralize(@question.question_comments.length, 'comments') %></h2>

<% @question.question_comments.each do |comment| %>
  <p><%= comment.body %> (<em><%= link_to comment.person.name, person_path(comment.person) %>, <%= time_ago_in_words(comment.created_at) %> ago</em>)</p>
  <p>&nbsp;</p>
<% end %>

<div id="add-a-comment-form" style="display: none;">
  <% semantic_form_for(@question_comment) do |f| %>
    <%= f.input :body, :input_html => { :rows => 10, :cols => 40 } %>
    <%= hidden_field_tag "question_comment[question_id]", @question.id %>
    <%= f.commit_button "Post Comment" %>
  <% end %>
</div>