config/routes.rb
Littlegeodesignworld::Application.routes.draw do
  root :to => "site#land"

  resources :question_comments
  resources :questions
  resources :action_item_comments
  resources :action_items
  resources :people
  
  match '/questions/:id/vote_up' => 'questions#vote_up', :as => :vote_up_question
  match '/action_items/:id/vote_up' => 'action_items#vote_up', :as => :vote_up_action_item
  match '/action_items/:id/take_on' => 'action_items#take_on', :as => :take_on_action_item

  devise_for :admins
  devise_for :persons
end

app/models/question_comment.rb
class QuestionComment < ActiveRecord::Base
  belongs_to :question
  belongs_to :person
end

app/controllers/question_comments_controller.rb
class QuestionCommentsController < ApplicationController
  before_filter :authenticate_person!
  
  # GET /question_comments
  # GET /question_comments.xml
  def index
    @question_comments = QuestionComment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @question_comments }
    end
  end

  # GET /question_comments/1
  # GET /question_comments/1.xml
  def show
    @question_comment = QuestionComment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @question_comment }
    end
  end

  # GET /question_comments/new
  # GET /question_comments/new.xml
  def new
    @question_comment = QuestionComment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @question_comment }
    end
  end

  # GET /question_comments/1/edit
  def edit
    @question_comment = QuestionComment.find(params[:id])
  end

  # POST /question_comments
  # POST /question_comments.xml
  def create
    @question_comment = QuestionComment.new(params[:question_comment])
    @question_comment.person = current_person

    respond_to do |format|
      if @question_comment.save
        format.html { redirect_to(@question_comment.question, :notice => "We've added your comment.") }
        format.xml  { render :xml => @question_comment, :status => :created, :location => @question_comment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @question_comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /question_comments/1
  # PUT /question_comments/1.xml
  def update
    @question_comment = QuestionComment.find(params[:id])

    respond_to do |format|
      if @question_comment.update_attributes(params[:question_comment])
        format.html { redirect_to(@question_comment, :notice => 'Question comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @question_comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /question_comments/1
  # DELETE /question_comments/1.xml
  def destroy
    @question_comment = QuestionComment.find(params[:id])
    @question_comment.destroy

    respond_to do |format|
      format.html { redirect_to(question_comments_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/question_comments_helper.rb
module QuestionCommentsHelper
end

app/views/question_comments/_form.html.erb
<%= form_for(@question_comment) do |f| %>
  <% if @question_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question_comment.errors.count, "error") %> prohibited this question_comment from being saved:</h2>

      <ul>
      <% @question_comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question_id %><br />
    <%= f.text_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :person_id %><br />
    <%= f.text_field :person_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/question_comments/edit.html.erb
<h1>Editing question_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @question_comment %> |
<%= link_to 'Back', question_comments_path %>

app/views/question_comments/index.html.erb
<h1>Listing question_comments</h1>

<table>
  <tr>
    <th>Question</th>
    <th>Person</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @question_comments.each do |question_comment| %>
  <tr>
    <td><%= question_comment.question_id %></td>
    <td><%= question_comment.person_id %></td>
    <td><%= question_comment.body %></td>
    <td><%= link_to 'Show', question_comment %></td>
    <td><%= link_to 'Edit', edit_question_comment_path(question_comment) %></td>
    <td><%= link_to 'Destroy', question_comment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question comment', new_question_comment_path %>

app/views/question_comments/new.html.erb
<h1>New question_comment</h1>

<%= render 'form' %>

<%= link_to 'Back', question_comments_path %>

app/views/question_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @question_comment.question_id %>
</p>

<p>
  <b>Person:</b>
  <%= @question_comment.person_id %>
</p>

<p>
  <b>Body:</b>
  <%= @question_comment.body %>
</p>


<%= link_to 'Edit', edit_question_comment_path(@question_comment) %> |
<%= link_to 'Back', question_comments_path %>