config/routes.rb
Littlegeodesignworld::Application.routes.draw do
  root :to => "site#land"

  resources :question_comments
  resources :questions
  resources :action_item_comments
  resources :action_items
  resources :people
  
  match '/questions/:id/vote_up' => 'questions#vote_up', :as => :vote_up_question
  match '/action_items/:id/vote_up' => 'action_items#vote_up', :as => :vote_up_action_item
  match '/action_items/:id/take_on' => 'action_items#take_on', :as => :take_on_action_item

  devise_for :admins
  devise_for :persons
end

app/models/action_item.rb
class ActionItem < ActiveRecord::Base
  belongs_to :person
  has_many :action_item_comments
  has_many :people_whove_taken_on, :source => :person, :through => :person_taking_on_action_items
  has_many :person_taking_on_action_items
end

app/controllers/action_items_controller.rb
class ActionItemsController < ApplicationController
  before_filter :authenticate_person!
  
  # GET /action_items
  # GET /action_items.xml
  def index
    @action_items = ActionItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @action_items }
    end
  end

  # GET /action_items/1
  # GET /action_items/1.xml
  def show
    @action_item = ActionItem.find(params[:id])
    
    @action_item_comment = ActionItemComment.new

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @action_item }
    end
  end

  # GET /action_items/new
  # GET /action_items/new.xml
  def new
    @action_item = ActionItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @action_item }
    end
  end

  # GET /action_items/1/edit
  def edit
    @action_item = ActionItem.find(params[:id])
  end

  # POST /action_items
  # POST /action_items.xml
  def create
    @action_item = ActionItem.new(params[:action_item])
    @action_item.person = current_person

    respond_to do |format|
      if @action_item.save
        format.html { redirect_to(@action_item, :notice => 'Action item was successfully created.') }
        format.xml  { render :xml => @action_item, :status => :created, :location => @action_item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @action_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /action_items/1
  # PUT /action_items/1.xml
  def update
    @action_item = ActionItem.find(params[:id])

    respond_to do |format|
      if @action_item.update_attributes(params[:action_item])
        format.html { redirect_to(@action_item, :notice => 'Action item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @action_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /action_items/1
  # DELETE /action_items/1.xml
  def destroy
    @action_item = ActionItem.find(params[:id])
    @action_item.destroy

    respond_to do |format|
      format.html { redirect_to(action_items_url) }
      format.xml  { head :ok }
    end
  end
  
  def vote_up
    @action_item = ActionItem.find(params[:id])
    if !@action_item.votes
      @action_item.votes = 0
    end
    @action_item.votes = @action_item.votes + 1

    respond_to do |format|
      if @action_item.save()
        format.html { redirect_to(@action_item, :notice => 'Your vote was recorded.') }
      end
    end
  end
  
  def take_on
    @action_item = ActionItem.find(params[:id])
    
    @person_taking_on_action_item = PersonTakingOnActionItem.new
    @person_taking_on_action_item.person = current_person
    @person_taking_on_action_item.action_item = @action_item
    
    respond_to do |format|
      if PersonTakingOnActionItem.where({:person_id => current_person.id, :action_item_id => @action_item.id}).length > 0
        format.html { redirect_to(@action_item, :notice => "Aren't you already signed up?") }
      elsif @person_taking_on_action_item.save()
        format.html { redirect_to(@action_item, :notice => 'You have been added to the list to help.') }
      end
    end
  end
end

app/helpers/action_items_helper.rb
module ActionItemsHelper
end

app/views/action_items/_form.html.erb
<%= form_for(@action_item) do |f| %>
  <% if @action_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@action_item.errors.count, "error") %> prohibited this action_item from being saved:</h2>

      <ul>
      <% @action_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit "Create action item"%>
  </div>
<% end %>

app/views/action_items/edit.html.erb
<h1>Editing action_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @action_item %> |
<%= link_to 'Back', action_items_path %>

app/views/action_items/index.html.erb
<h1>Listing action_items</h1>

<table>
  <tr>
    <th>Author</th>
    <th>Approved</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @action_items.each do |action_item| %>
  <tr>
    <td><%= action_item.author_id %></td>
    <td><%= action_item.approved %></td>
    <td><%= action_item.body %></td>
    <td><%= link_to 'Show', action_item %></td>
    <td><%= link_to 'Edit', edit_action_item_path(action_item) %></td>
    <td><%= link_to 'Destroy', action_item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Action item', new_action_item_path %>

app/views/action_items/new.html.erb
<h1><img src="/images/logo.png" alt="GeodesignWorld"/>
<h2>Add an Action Item</h2>

<%= render 'form' %>

<p><%= link_to 'Never mind. Take me back to the main page.', root_path %></p>

app/views/action_items/show.html.erb
<% content_for :head do %>
<script>
$(document).ready(function() {
  $('#add-a-comment-link').click(function() {
    $('#add-a-comment-link').hide();
    $('#add-a-comment-form').show();
  });
});
</script>
<style>
label {
  display: none;
}
</style>
<% end %>

<h1><a href="/"><img src="/images/logo.png" alt="GeodesignWorld"/></a></h1>
<%= link_to 'Take me back to the main page.', root_path, :id => 'sign-out-block' %>
<h2>An Action Item</h2>

<p style="font-size:24px;"><%= @action_item.body %></p>
<p>&nbsp;</p>
<p><%= pluralize(@action_item.votes, 'vote') %> <%= link_to "This is good. Add my vote.", vote_up_action_item_path(@action_item) %></p>
<p>&nbsp;</p>

<%= link_to "I'd like to help, too.", take_on_action_item_path(@action_item), :id => 'sign-up-to-help-link' %>
<h2><%= pluralize(@action_item.people_whove_taken_on.length, 'person has') %> signed up to help with this action item.</h2>
<ul>
<% @action_item.people_whove_taken_on.each do |p| %>
  <li><%= link_to p.name, person_path(p) %></li>
<% end %>
</ul>

<a href="#" id="add-a-comment-link">Add a Comment</a>
<h2><%= pluralize(@action_item.action_item_comments.length, 'comment') %></h2>

<% @action_item.action_item_comments.each do |comment| %>
  <p><%= comment.body %> (<em><%= link_to comment.person.name, person_path(comment.person) %>, <%= time_ago_in_words(comment.created_at) %> ago</em>)</p>
  <p>&nbsp;</p>
<% end %>

<div id="add-a-comment-form" style="display: none;">
  <% semantic_form_for(@action_item_comment) do |f| %>
    <%= f.input :body, :input_html => { :rows => 10, :cols => 40 } %>
    <%= hidden_field_tag "action_item_comment[action_item_id]", @action_item.id %>
    <%= f.commit_button "Post Comment" %>
  <% end %>
</div>